/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package doan;

import java.awt.BorderLayout;
import java.awt.Color;
import java.sql.*;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import java.util.logging.Logger;
import java.util.logging.Level;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author Admin
 */
public class DangKy extends javax.swing.JPanel {

    /**
     * Creates new form DangKy1
     */
    
    public DangKy() {
        initComponents();
        ButtonGroup bg1 = new ButtonGroup();
        bg1.add(jRadioButton_Male);
        bg1.add(jRadioButton_Female);
        jRadioButton_Male.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField_Name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField_User = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPasswordField_Pass = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jPasswordField_Confirm = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jTextField_Phone = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField_Email = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jRadioButton_Male = new javax.swing.JRadioButton();
        jRadioButton_Female = new javax.swing.JRadioButton();
        jButton_Register = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 204, 51));

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel2.setText("Họ Tên:");

        jTextField_Name.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jTextField_Name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_NameKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel3.setText("Tài Khoản:");

        jTextField_User.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jTextField_User.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_UserKeyTyped(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel4.setText("Mật Khẩu:");

        jPasswordField_Pass.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jPasswordField_Pass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jPasswordField_PassKeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel5.setText("Nhập Lại Mật Khẩu:");

        jPasswordField_Confirm.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jPasswordField_Confirm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jPasswordField_ConfirmKeyTyped(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel6.setText("SĐT:");

        jTextField_Phone.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jTextField_Phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_PhoneActionPerformed(evt);
            }
        });
        jTextField_Phone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_PhoneKeyTyped(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel10.setText("EMAIL:");

        jTextField_Email.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jTextField_Email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_EmailActionPerformed(evt);
            }
        });
        jTextField_Email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_EmailKeyTyped(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel7.setText("Giới Tính:");

        jRadioButton_Male.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jRadioButton_Male.setText("Nam");
        jRadioButton_Male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_MaleActionPerformed(evt);
            }
        });

        jRadioButton_Female.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jRadioButton_Female.setText("Nữ");

        jButton_Register.setBackground(new java.awt.Color(102, 255, 255));
        jButton_Register.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton_Register.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Register.setText("Đăng Ký");
        jButton_Register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_RegisterActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(102, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 255, 0)));

        jLabel8.setBackground(new java.awt.Color(102, 255, 255));
        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("ĐĂNG KÝ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel10)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField_User)
                            .addComponent(jTextField_Name, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jRadioButton_Male)
                                .addGap(41, 41, 41)
                                .addComponent(jRadioButton_Female)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jPasswordField_Pass, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPasswordField_Confirm, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_Phone, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_Email, javax.swing.GroupLayout.Alignment.LEADING))))
                .addGap(199, 199, 199))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(223, 223, 223)
                .addComponent(jButton_Register, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_User, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordField_Pass, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordField_Confirm, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_Phone, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton_Male)
                    .addComponent(jRadioButton_Female))
                .addGap(88, 88, 88)
                .addComponent(jButton_Register, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_NameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_NameKeyTyped
        if (jTextField_Name.getText().length() >= 50 ){
            evt.consume();
        }
    }//GEN-LAST:event_jTextField_NameKeyTyped

    private void jTextField_UserKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_UserKeyTyped
        if (jTextField_User.getText().length() >= 30 ){
            evt.consume();
        }
    }//GEN-LAST:event_jTextField_UserKeyTyped

    private void jPasswordField_PassKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField_PassKeyTyped
        if (jPasswordField_Pass.getText().length() >= 30 ){
            evt.consume();
        }
    }//GEN-LAST:event_jPasswordField_PassKeyTyped

    private void jPasswordField_ConfirmKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField_ConfirmKeyTyped
        if (jPasswordField_Confirm.getText().length() >= 30 ){
            evt.consume();
        }
    }//GEN-LAST:event_jPasswordField_ConfirmKeyTyped

    private void jTextField_PhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_PhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_PhoneActionPerformed

    private void jTextField_PhoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_PhoneKeyTyped
        char c = evt.getKeyChar();
        if(!Character.isDigit(c)){
            evt.consume();
        }
        if (jTextField_Phone.getText().length() >= 10 ){
            evt.consume();
        }
    }//GEN-LAST:event_jTextField_PhoneKeyTyped

    private void jTextField_EmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_EmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_EmailActionPerformed

    private void jTextField_EmailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_EmailKeyTyped
        if (jTextField_Email.getText().length() >= 50 ){
            evt.consume();
        }
    }//GEN-LAST:event_jTextField_EmailKeyTyped

    private void jRadioButton_MaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_MaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton_MaleActionPerformed

    private void jButton_RegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_RegisterActionPerformed

        String name = ChuanHoa.chuanHoaHoTen(jTextField_Name.getText());
        String user = jTextField_User.getText();
        String password = String.valueOf(jPasswordField_Pass.getPassword());
        String confirmPass = String.valueOf(jPasswordField_Confirm.getPassword());
        String phone = jTextField_Phone.getText();
        String email = jTextField_Email.getText();
        String gender = jRadioButton_Male.isSelected() == true ? "Nam" : "Nữ";
        String date = "";
        int KTName = 0, KTUser = 0, KTPass = 0, KTConfirm = 0, KTPhone = 0,KTEmail = 0, KTGender = 0, KTDate = 0;
        if(name.equals("")){
            KTName = 1;
            JOptionPane.showMessageDialog(this, "Họ Tên Không Được Để Trống!!!");
        }
        else if(user.equals("")){
            KTUser = 1;
            JOptionPane.showMessageDialog(this, "Tài Khoản Không Được Để Trống!!!");
        }
        else if(password.equals("")){
            KTPass = 1;
            JOptionPane.showMessageDialog(this, "Mật Khẩu Không Được Để Trống!!!");
        }
        else if(phone.equals("")){
            KTPhone = 1;
            JOptionPane.showMessageDialog(this, "Số Điện Thoại Không Được Để Trống!!!");
        }
        else if(!ChuanHoa.kiemTraPhone(phone)){
            KTPhone = 1;
            JOptionPane.showMessageDialog(this, "Số Điện Thoại Không Hợp Lệ!!!");
        }
        else if(email.equals("")){
            KTEmail = 1;
            JOptionPane.showMessageDialog(this, "Email Không Được Để Trống!!!");
        }
        else if(!ChuanHoa.kiemTraEmail(email)){
            KTEmail = 1;
            JOptionPane.showMessageDialog(this, "Email Không Hợp Lệ!!!");
        }
        else if(!password.equals(confirmPass)){
            KTConfirm = 1;
            JOptionPane.showMessageDialog(this, "Mật Khẩu Không Khớp!!!");
        }
        else if(password.length() < 6 || password.length() > 30){
            KTPass = 1;
            JOptionPane.showMessageDialog(this, "Mật Khẩu Từ 6 - 30 Kí Tự!!!");
        }

        else if(KTName != 1 && KTUser != 1 && KTPass != 1 && KTConfirm != 1 && KTPhone != 1 && KTGender != 1 && KTDate != 1 && KTEmail != 1){
            int check = kiemTraUser(user);
            int check1 = kiemTraEmail(email);
            int check2 = kiemTraSDT(phone);
            if(check == 1 ){
                JOptionPane.showMessageDialog(this, "Tài Khoản Đã Tồn Tại!!!");
            }
            if(check1 == 1){
                JOptionPane.showMessageDialog(this, "Email Đã Tồn Tại!!!");
            }
            if(check2 == 1){
                JOptionPane.showMessageDialog(this, "Số Điện Thoại Đã Tồn Tại!!!");
            }
            else if(check != 1 && check1 != 1 && check2 != 1){
                luuDangKy(name, user, password, phone, email, gender, "Nhân Viên");
                JOptionPane.showMessageDialog(this, "Đăng Ký Thành Công!!");
                
            }
        }

    }//GEN-LAST:event_jButton_RegisterActionPerformed
    private void luuDangKy(String name, String user, String pass, String phone, String email, String gender, String position ){
        Connection ketNoi = KetNoiSQL.layKetNoi();
        String sql = "insert into NHANVIEN values (?, ?, ?, ?, ?, ?, ?)";
        try{
            PreparedStatement ps = ketNoi.prepareStatement(sql);
            ps.setString(1, name);
            ps.setString(2, user);
            ps.setString(3, pass);
            ps.setString(4, phone);
            ps.setString(5, email);
            ps.setString(6, gender);
            ps.setString(7, position);
            ps.executeUpdate();
            
        }
        catch(SQLException ex){
            Logger.getLogger(DangKy.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private int kiemTraUser(String user){
        Connection ketNoi = KetNoiSQL.layKetNoi();
        int tontai = 0;
        String sql = "select * from NHANVIEN where TAIKHOAN = '" + user + "'";
        try{
            try (PreparedStatement ps = ketNoi.prepareStatement(sql); ResultSet rs = ps.executeQuery()) {
                while(rs.next()){
                    tontai = 1;
                }
            }
            ketNoi.close();
        }
        catch(SQLException ex){
            Logger.getLogger(DangKy.class.getName()).log(Level.SEVERE, null, ex);
        }
        return tontai;
    }
        private int kiemTraEmail(String email){
        Connection ketNoi = KetNoiSQL.layKetNoi();
        int tontai = 0;
        String sql = "select * from NHANVIEN";
        try{
            try (PreparedStatement ps = ketNoi.prepareStatement(sql); ResultSet rs = ps.executeQuery()) {
                while(rs.next()){
                    if(rs.getString("EMAIL").trim().equals(email)){
                        tontai = 1;
                    }
                }
            }
            ketNoi.close();
        }
        catch(SQLException ex){
            Logger.getLogger(DangKy.class.getName()).log(Level.SEVERE, null, ex);
        }
        return tontai;
    }
        private int kiemTraSDT(String phone){
        Connection ketNoi = KetNoiSQL.layKetNoi();
        int tontai = 0;
        String sql = "select * from NHANVIEN";
        try{
            try (PreparedStatement ps = ketNoi.prepareStatement(sql); ResultSet rs = ps.executeQuery()) {
                while(rs.next()){
                    if(rs.getString("SDT").equals(phone)){
                        tontai = 1;
                    }
                }
            }
            ketNoi.close();
        }
        catch(SQLException ex){
            Logger.getLogger(DangKy.class.getName()).log(Level.SEVERE, null, ex);
        }
        return tontai;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Register;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField jPasswordField_Confirm;
    private javax.swing.JPasswordField jPasswordField_Pass;
    private javax.swing.JRadioButton jRadioButton_Female;
    private javax.swing.JRadioButton jRadioButton_Male;
    private javax.swing.JTextField jTextField_Email;
    private javax.swing.JTextField jTextField_Name;
    private javax.swing.JTextField jTextField_Phone;
    private javax.swing.JTextField jTextField_User;
    // End of variables declaration//GEN-END:variables

    private void dispose() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
