/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package doan;

import java.awt.BorderLayout;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;

/**
 *
 * @author Admin
 */
public class ThongTin extends javax.swing.JPanel {

    /**
     * Creates new form ThongTin
     */
    private String username = "";
    public ThongTin(String username){
        this.username = username;
        initComponents();
        if(layChucVu(username).equals("Nhân Viên")){
            jButton_ThongTinMyPham.setVisible(false);
            jButton_ThongTinDungCu.setVisible(false);
            jButton_ThongTinTinhTrang.setBackground(Color.GREEN);
            JPanel node = new ThongTinTinhTrang(username);
            jPanel_MenuThongTin.removeAll();
            jPanel_MenuThongTin.setLayout(new BorderLayout());
            jPanel_MenuThongTin.add(node);
            jPanel_MenuThongTin.validate();
            jPanel_MenuThongTin.repaint();
        }
        else{
            jButton_ThongTinMyPham.setBackground(Color.GREEN);
            jButton_ThongTinDungCu.setBackground(Color.CYAN);
            jButton_ThongTinTinhTrang.setBackground(Color.CYAN);
            JPanel node = new ThongTinMyPham(username);
            jPanel_MenuThongTin.removeAll();
            jPanel_MenuThongTin.setLayout(new BorderLayout());
            jPanel_MenuThongTin.add(node);
            jPanel_MenuThongTin.validate();
            jPanel_MenuThongTin.repaint();
        }
        
    }
    public ThongTin() {
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_MenuThongTin = new javax.swing.JPanel();
        jButton_ThongTinMyPham = new javax.swing.JButton();
        jButton_ThongTinDungCu = new javax.swing.JButton();
        jButton_ThongTinTinhTrang = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout jPanel_MenuThongTinLayout = new javax.swing.GroupLayout(jPanel_MenuThongTin);
        jPanel_MenuThongTin.setLayout(jPanel_MenuThongTinLayout);
        jPanel_MenuThongTinLayout.setHorizontalGroup(
            jPanel_MenuThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel_MenuThongTinLayout.setVerticalGroup(
            jPanel_MenuThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 611, Short.MAX_VALUE)
        );

        jButton_ThongTinMyPham.setBackground(new java.awt.Color(0, 255, 255));
        jButton_ThongTinMyPham.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton_ThongTinMyPham.setText("MỸ PHẨM");
        jButton_ThongTinMyPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ThongTinMyPhamActionPerformed(evt);
            }
        });

        jButton_ThongTinDungCu.setBackground(new java.awt.Color(0, 255, 255));
        jButton_ThongTinDungCu.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton_ThongTinDungCu.setText("DỤNG CỤ");
        jButton_ThongTinDungCu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ThongTinDungCuActionPerformed(evt);
            }
        });

        jButton_ThongTinTinhTrang.setBackground(new java.awt.Color(0, 255, 255));
        jButton_ThongTinTinhTrang.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton_ThongTinTinhTrang.setText("TÌNH TRẠNG");
        jButton_ThongTinTinhTrang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ThongTinTinhTrangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_MenuThongTin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jButton_ThongTinTinhTrang, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addComponent(jButton_ThongTinMyPham, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87)
                .addComponent(jButton_ThongTinDungCu, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_ThongTinMyPham, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_ThongTinDungCu, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_ThongTinTinhTrang, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel_MenuThongTin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_ThongTinMyPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ThongTinMyPhamActionPerformed
        jButton_ThongTinMyPham.setBackground(Color.GREEN);
        jButton_ThongTinDungCu.setBackground(Color.CYAN);
        jButton_ThongTinTinhTrang.setBackground(Color.CYAN);
        JPanel node = new ThongTinMyPham(username);
        jPanel_MenuThongTin.removeAll();
        jPanel_MenuThongTin.setLayout(new BorderLayout());
        jPanel_MenuThongTin.add(node);
        jPanel_MenuThongTin.validate();
        jPanel_MenuThongTin.repaint();
    }//GEN-LAST:event_jButton_ThongTinMyPhamActionPerformed

    private void jButton_ThongTinDungCuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ThongTinDungCuActionPerformed
        jButton_ThongTinMyPham.setBackground(Color.CYAN);
        jButton_ThongTinDungCu.setBackground(Color.GREEN);
        jButton_ThongTinTinhTrang.setBackground(Color.CYAN);
        JPanel node = new ThongTinDungCu(username);
        jPanel_MenuThongTin.removeAll();
        jPanel_MenuThongTin.setLayout(new BorderLayout());
        jPanel_MenuThongTin.add(node);
        jPanel_MenuThongTin.validate();
        jPanel_MenuThongTin.repaint();
    }//GEN-LAST:event_jButton_ThongTinDungCuActionPerformed

    private void jButton_ThongTinTinhTrangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ThongTinTinhTrangActionPerformed
        jButton_ThongTinMyPham.setBackground(Color.CYAN);
        jButton_ThongTinDungCu.setBackground(Color.CYAN);
        jButton_ThongTinTinhTrang.setBackground(Color.GREEN);
        JPanel node = new ThongTinTinhTrang(username);
        jPanel_MenuThongTin.removeAll();
        jPanel_MenuThongTin.setLayout(new BorderLayout());
        jPanel_MenuThongTin.add(node);
        jPanel_MenuThongTin.validate();
        jPanel_MenuThongTin.repaint();
    }//GEN-LAST:event_jButton_ThongTinTinhTrangActionPerformed
    private String layChucVu(String username){
        Connection ketNoi = KetNoiSQL.layKetNoi();
        String sql = "select CHUCVU from NHANVIEN WHERE TAIKHOAN = '" + username + "'";
        String kt = "";
        try{
            PreparedStatement ps = ketNoi.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            while(rs.next()){
                kt = rs.getString("CHUCVU").trim();
            }
            ketNoi.close();
            
        }
        catch(SQLException ex){
            Logger.getLogger(ThongTinNhanVien.class.getName()).log(Level.SEVERE, null, ex);
        }
        return kt;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_ThongTinDungCu;
    private javax.swing.JButton jButton_ThongTinMyPham;
    private javax.swing.JButton jButton_ThongTinTinhTrang;
    private javax.swing.JPanel jPanel_MenuThongTin;
    // End of variables declaration//GEN-END:variables
}
